Update segmentation fault catching policy

diff --git a/image/scripts/check b/image/scripts/check
--- a/image/scripts/check
+++ b/image/scripts/check
@@ -36,8 +36,17 @@ then
     fi
     cp ${GITLAB_USER_LOGIN}_$2_lib.so /sandbox
     echo -e "\033[0;34mCHECK STRATEGY SAFETY\033[0m"
-    PYTHONPATH='/' python /games/$4/$5
-    echo -e "\033[0;32mCHECK PASSED\033[0m\n"
+    PYTHONPATH='/' python /games/$4/$5 > temp.txt |:
+    SEGFAULT="$(cat temp.txt)n"
+    if [ "$SEGFAULT" = 'n' ]
+    then
+        echo -e "\033[0;31mCHECK FAILED. SEGFAULT OCCURED\033[0m\n"
+        rm -f temp.txt
+        exit 1
+    else
+        echo -e "\033[0;32mCHECK PASSED\033[0m\n"
+        rm -f temp.txt
+    fi 
 else
     echo -e "\033[0;31m${GAME_PATH}${GITLAB_USER_LOGIN}_$2.c NOT FOUND\033[0m\n"
 fi
