Rollback hyperflex decision checker

diff --git a/image/scripts/strgame b/image/scripts/strgame
--- a/image/scripts/strgame
+++ b/image/scripts/strgame
@@ -4,54 +4,40 @@ COMPILE_FLAGS="-Werror -Wall -Wextra -Wpedantic -Wcast-align -Wcast-qual \
 -Wconversion -Wenum-compare -Wfloat-equal  -Wredundant-decls -Wsign-conversion -c -O3"
 GAME_PATH="STRgame/"
 
-if [ -e ${GAME_PATH}round.txt ]
+if [ -e ${GAME_PATH}${GITLAB_USER_LOGIN}_split.c ]
 then
-    DECISION=$(cat ${GAME_PATH}round.txt | sed 's/\(.*\)/\1/' | tr '[:upper:]' '[:lower:]' | sed 's/ //g');
-    if [ "$DECISION" != 'go' ]
+    echo -e "\033[0;32m${GAME_PATH}${GITLAB_USER_LOGIN}_split.c FOUND\033[0m";
+    SYS=$(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_split.c | sed -n 's/\(system(".*");\)/\1/p')y;
+    FORK=$(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_split.c | sed -n 's/\(fork();\)/\1/p')y;
+    EXEC=$(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_split.c | sed -n 's/\(exec.{0,4}(.*);\)/\1/p')y;
+    if [ "$SYS" != 'y' ] || [ "$FORK" != 'y' ] || [ "$EXEC" != 'y' ]
     then
-        echo -e "\033[0;35m${GITLAB_USER_LOGIN} IS NOT READY TO PARTICIPATE\033[0m";
-        exit 0;
+        echo -e "\033[0;31mSPAM FOUND IN ${GAME_PATH}${GITLAB_USER_LOGIN}_split.c\033[0m";
+        exit 1;
     else
-        echo -e "\033[0;34m${GITLAB_USER_LOGIN} READY TO PARTICIPATE\033[0m";
-        if [ -e ${GAME_PATH}${GITLAB_USER_LOGIN}_split.c ]
-        then
-            echo -e "\033[0;32m${GAME_PATH}${GITLAB_USER_LOGIN}_split.c FOUND\033[0m";
-            SYS=$(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_split.c | sed -n 's/\(system(".*");\)/\1/p')y;
-            FORK=$(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_split.c | sed -n 's/\(fork();\)/\1/p')y;
-            EXEC=$(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_split.c | sed -n 's/\(exec.{0,4}(.*);\)/\1/p')y;
-            if [ "$SYS" != 'y' ] || [ "$FORK" != 'y' ] || [ "$EXEC" != 'y' ]
-            then
-                echo -e "\033[0;31mSPAM FOUND IN ${GAME_PATH}${GITLAB_USER_LOGIN}_split.c\033[0m";
-                exit 1;
-            else
-                echo -e "\033[0;32mNO SPAM FOUND IN ${GAME_PATH}${GITLAB_USER_LOGIN}_split.c\033[0m";
-                gcc ${COMPILE_FLAGS} -fpic ${GAME_PATH}${GITLAB_USER_LOGIN}_split.c;
-                gcc -shared -o ${GITLAB_USER_LOGIN}_split_lib.so ${GITLAB_USER_LOGIN}_split.o;
-            fi
-        else
-            echo -e "\033[0;31m${GAME_PATH}${GITLAB_USER_LOGIN}_split.c NOT FOUND\033[0m";
-        fi
-
-        if [ -e ${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c ]
-        then
-            echo -e "\033[0;32m${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c FOUND\033[0m";
-            SYS=$(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c | sed -n 's/\(system(".*");\)/\1/p')y;
-            FORK=$(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c | sed -n 's/\(fork();\)/\1/p')y;
-            EXEC=$(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c | sed -n 's/\(exec.{0,4}(.*);\)/\1/p')y;
-            if [ "$SYS" != 'y' ] || [ "$FORK" != 'y' ] || [ "$EXEC" != 'y' ] 
-            then
-                echo -e "\033[0;31mSPAM FOUND IN ${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c\033[0m";
-                exit 1;
-            else
-                echo -e "\033[0;32mNO SPAM FOUND IN ${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c\033[0m";
-                gcc ${COMPILE_FLAGS} -fpic ${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c;
-                gcc -shared -o ${GITLAB_USER_LOGIN}_strtok_lib.so ${GITLAB_USER_LOGIN}_strtok.o;
-            fi
-        else
-            echo -e "\033[0;31m${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c NOT FOUND\033[0m";
-        fi
+        echo -e "\033[0;32mNO SPAM FOUND IN ${GAME_PATH}${GITLAB_USER_LOGIN}_split.c\033[0m";
+        gcc ${COMPILE_FLAGS} -fpic ${GAME_PATH}${GITLAB_USER_LOGIN}_split.c;
+        gcc -shared -o ${GITLAB_USER_LOGIN}_split_lib.so ${GITLAB_USER_LOGIN}_split.o;
     fi
 else
-    echo -e "\033[0;31m${GAME_PATH}round.txt NOT FOUND\033[0m";
-    exit 1;
+    echo -e "\033[0;31m${GAME_PATH}${GITLAB_USER_LOGIN}_split.c NOT FOUND\033[0m";
+fi
+
+if [ -e ${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c ]
+then
+    echo -e "\033[0;32m${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c FOUND\033[0m";
+    SYS=$(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c | sed -n 's/\(system(".*");\)/\1/p')y;
+    FORK=$(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c | sed -n 's/\(fork();\)/\1/p')y;
+    EXEC=$(cpp ${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c | sed -n 's/\(exec.{0,4}(.*);\)/\1/p')y;
+    if [ "$SYS" != 'y' ] || [ "$FORK" != 'y' ] || [ "$EXEC" != 'y' ] 
+    then
+        echo -e "\033[0;31mSPAM FOUND IN ${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c\033[0m";
+        exit 1;
+    else
+        echo -e "\033[0;32mNO SPAM FOUND IN ${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c\033[0m";
+        gcc ${COMPILE_FLAGS} -fpic ${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c;
+        gcc -shared -o ${GITLAB_USER_LOGIN}_strtok_lib.so ${GITLAB_USER_LOGIN}_strtok.o;
+    fi
+else
+    echo -e "\033[0;31m${GAME_PATH}${GITLAB_USER_LOGIN}_strtok.c NOT FOUND\033[0m";
 fi
